name: "Run bot 🤖"

on:
  schedule:
    - cron: "*/5 * * * 1,2,3,4,5"
  workflow_dispatch:

permissions:
  actions: write
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update_model_list:
    name: "Run earnings bot"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --only main

      - name: Get the latest earnings results
        run: poetry run python earnings/run.py
        env:
          PYTHONUNBUFFERED: 1
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Commit and push if it changed
        run: |-
          git config user.name "Major Hayden"
          git config user.email "major@mhtx.net"
          git add last_message_id.txt
          timestamp=$(date -u)
          git commit -m "Updating last message seen: ${timestamp}" || exit 0
          git clean -fxd
          git status
          git pull --rebase
          git push
